-- Auto-generated from Employees.xlsx — do not hand-edit, regenerate instead.
truncate table request_audit_log, requests, employees restart identity;
insert into employees (name, title, city, branch, phone, email) values
('Khaled Alarrad', 'Service Manager', 'Abha', 'King Fahad', '565554131', 'khaled.alarrad@jiadmotors.com'),
('Ahmed Mufeed Mahmoud', 'Head of service', 'Jeddah', 'Head Office', '508969157', 'Ahmed.Mahmod@jiadmotors.com'),
('Ashwaq Alanazi', 'Customer Complaints Supervisor', 'Jeddah', 'Head Office', '547427078', 'ashwaq.alenezi@jiadmotors.com'),
('Adil Saleh Almakhlafi', 'Service Manager', 'Dammam', 'Khaldiah', '550888380', 'adil.almakhlafi@jiadmotors.com'),
('Salih Ismail Elsayed', 'Service Manager', 'Madinah', 'Airport Road', '544548018', 'saleh.ismail@jiadmotors.com'),
('Amaal Algrigri', 'Customer Complaints Executive', 'Jeddah', 'Head Office', '505586759', 'amal.hamdan@jiadmotors.com'),
('Khaled Alghamdi', 'Customer Complaints Executive', 'Jeddah', 'Head Office', '560602055', 'Khaled.Alghamdy@jiadmotors.com'),
('Mehad Aljehani', 'Customer Complaints Executive', 'Jeddah', 'Head Office', '580133615', 'Mehad.Aljehani@jiadmotors.com​'),
('Ahmed Gomaa Sayed Mohammed', 'Service Manager', 'Jeddah', 'Hiraa', '565906920', 'ahmed.gomaa@jiadmotors.com'),
('Ahmed Nader Abdelaziz', 'Service Manager', 'Riyadh', 'North', '570415813', 'ahmed.nader@jiadmotors.com'),
('ELHASSAN BELKASMI', 'Technical Manager', 'Jeddah', 'Head Office', '541330400', NULL),
('Mohammed Osama Abu Ahmad', 'Parts Manager', 'Jeddah', 'Head Office', '503644756', 'Mohammed.osama@jiadmotors.com'),
('Ahmed Ibrahim Tayel', 'Service Manager', 'Jeddah', 'Nakheel', '566299010', 'ahmed.tayel@jiadmotors.com'),
('Fahd Saleh Ahmed Omar', 'Wholesale Parts Supervisor', 'Riyadh', 'North', NULL, 'Fahad.Omar@jiadmotors.com'),
('Muhammad Adam Muhammad Siddiq', 'Parts Supervisor', 'Jeddah', 'Hiraa', '596999591', 'Mohammed.Siddiq@jiadmotors.com'),
('Ahmed Hablil', 'Workshop Supervisor', 'Jeddah', 'Madinah Road', '566469717', 'Ahmed.Hablil@jiadmotors.com'),
('Mohammad Babgi', 'Workshop Supervisor', 'Jeddah', 'Nakheel', '503525282', 'Mohammad.Babqi@jiadmotors.com'),
('Rami Kamli', 'Parts Supervisor', 'Jizan', 'Alsafa', '509872257', 'Rami.Kamli@jiadmotors.com'),
('Ahmed Mustafa Ahmed', 'Customer Experience Manager', 'Jeddah', 'Head Office', '538072563', 'Ahmad.Mustafa@jiadmotors.com'),
('Anad Alsayyali', 'Service Supervisor', 'Jeddah', 'Hiraa', '504772394', 'anad.alsayyali@jiadmotors.com'),
('Hussain Alhumaidi', 'Parts Supervisor', 'Dammam', 'Khaldiah', '545790001', 'hussain.alhumaidi@jiadmotors.com'),
('Sulaman Paracha', 'Parts Supervisor', 'Riyadh', 'Alsalih', '571636874', 'Sulaman.Paracha@jiadmotors.com'),
('Adam Tarek Makboul', 'Service Supervisor', 'Dammam', 'Khaldiah', '537627847', 'adam.makboul@jiadmotors.com'),
('Moaaz Shabaan Elsayed', 'Workshop Supervisor', 'Jeddah', 'Hiraa', '538680531', 'Moaaz.Shabaan@jiadmotors.com'),
('Irfan Syed Ahmed', 'Workshop Supervisor', 'Riyadh', 'Alsalih', '599070374', 'Irfan.Ahmed@jiadmotors.com'),
('Zaki Alsheikh', 'Trainer', 'Jeddah', 'Head Office', '569216882', 'Zaki.Alsheikh@jiadmotors.com'),
('Osman Ahmed', 'Service Supervisor', 'Riyadh', 'Alsalih', '538457172', 'osman.ahmed@jiadmotors.com'),
('Karim Hussein Abdelwahab Mohamed', 'Workshop Supervisor', 'Madinah', 'Airport Road', '545866460', 'Kareem.Mohammed@jiadmotors.com​'),
('Ahmad Hamdani', 'Warranty Officer', 'Jeddah', 'Hiraa', '591766300', 'ahmad.hamdani@jiadmotors.com'),
('Ansar Bawajeeh', 'Warranty Officer', 'Jeddah', 'Head Office', '531196661', 'Ansar.Bawajeeh@jiadmotors.com'),
('Ibrahim Abdalla Ibrahim Mohamedali', 'Parts Supervisor', 'Riyadh', 'North', '563244576', 'ibrahim.mohamed@jiadmotors.com'),
('Younes Mohamed Younes Elmasry', 'Workshop Supervisor', 'Dammam', 'Khaldiah', '570755388', 'younes.elmasryi@jiadmotors.com'),
('Sabeel Ismail Majal', 'Parts Supervisor', 'Jeddah', 'Hiraa', '565766563', 'Sabeel.Ismail@jiadmotors.com'),
('Muhammad Waqar Amin', 'Parts Inventory Supervisor', 'Jeddah', 'Head Office', '544594228', 'muhammad.amin@jiadmotors.com'),
('Mohammed Amin Bakheribah', 'Service Supervisor', 'Riyadh', 'North', '542491758', 'mohammed.bakheribah@jiadmotors.com'),
('Basmah Almutairi', 'Service Advisor', 'Jeddah', 'Madinah Road', '591704714', 'Basmah.Almutairi@jiadmotors.com'),
('Rayan Alyazidi', 'Parts Advisor', 'Jeddah', 'Hiraa', '530097860', 'Rayan.Alyazidi@jiadmotors.com'),
('Mehdi Binabicha', 'Warranty Officer', 'Dammam', 'Khaldiah', '541966396', 'Mehdi.Binabicha@jiadmotors.com'),
('Khalid Almatrafi', 'Service Advisor', 'Jeddah', 'Madinah Road', '561681163', 'khalid.almatrfi@jiadmotors.com'),
('Abdullah Alammar', 'Receptionist', 'Riyadh', 'Alsalih', '580446464', 'Abdullah.Alammar@jiadmotors.com'),
('Yahya Alshowiki', 'Quality Controller', 'Dammam', 'Khaldiah', '544332776', 'yahya.alshowiki@jiadmotors.com'),
('Mohammed Alkhalifah', 'Service Advisor', 'Dammam', 'Khaldiah', '541271822', 'Mohammed.Alkhalifah@jiadmotors.com'),
('Ghada Alharbi', 'Parts Advisor', 'Jeddah', 'Hiraa', '563541343', 'ghadah.alharbi@jiadmotors.com'),
('Sultan Almalki', 'Receptionist', 'Jeddah', 'Nakheel', '564504855', 'Sultan.Almalki@jiadmotors.com'),
('Parawaiz Syed', 'Workshop Controller', 'Abha', 'King Fahad', '568749662', 'Parwiz.Syed@jiadmotors.com'),
('Bader Alanazi', 'Parts Advisor', 'Riyadh', 'Khurais', '500472499', 'Bader.Alanazi@jiadmotors.com'),
('Ahmed Wali Shutaifi', 'Parts Advisor', 'Dammam', 'Khaldiah', '592226672', 'Ahmed.Shutaifi@jiadmotors.com'),
('Alhasan Alhunaiti', 'Warranty Supervisor', 'Jeddah', 'Head Office', '541190981', 'Alhasan.Alhunaiti@jiadmotors.com'),
('Vinay Kaul', 'Head of Parts', 'Jeddah', 'Head Office', '556329617', 'Vinay.Kaul@jiadmotors.com'),
('Mohammed Makram', 'Parts Advisor', 'Riyadh', 'Alsalih', '556613710', 'Mohammed.Makram@jiadmotors.com'),
('AKANEETH SURENDRAN', 'Workshop Controller', 'Riyadh', 'Alsalih', '559918371', 'Akaneeth.Surendran@jiadmotors.com'),
('IMRAN JAFARKHAN PATHAN', 'Workshop Controller', 'Jeddah', 'Hiraa', '553610741', NULL),
('SURIYAN RAMU', 'Workshop Controller', 'Dammam', 'Khaldiah', '553794011', NULL),
('Muath Alkabsi', 'Data Analyst', 'Jeddah', 'Head Office', '503863534', 'Muath.Alkabsi@jiadmotors.com'),
('Khurram Shahzad', 'Workshop Team Leader', 'Riyadh', 'Alsalih', '592186619', NULL),
('Hussain Saleh Hasan', 'Parts Advisor', 'Dammam', 'Khaldiah', '557007900', 'hussain.hasan@jiadmotors.com'),
('Essa Alshamekh', 'Parts Advisor', 'Qassim', 'Buraidah', '551364272', 'Essa.alshamekh@jiadmotors.com'),
('Hamzah Akmubarak', 'Receptionist', 'Dammam', 'Khaldiah', '569449155', 'hamzah.almubarak@jiadmotors.com'),
('Khalid Saleh Albloshi', 'Service Advisor', 'Madinah', 'Airport Road', '599961246', 'Khaled.Albloshi@jiadmotors.com'),
('Farhan Ansari', 'Parts Advisor', 'Jeddah', 'Head Office', '537154957', 'farhan.ansari@jiadmotors.com'),
('Amr Youssri Elsherbini', 'Service Advisor', 'Jeddah', 'Hiraa', '569070780', 'amr.elsherbini@jiadmotors.com'),
('Omar Gad Atta Aboelsoud', 'Service Advisor', 'Riyadh', 'Alsalih', '539761819', 'Omar.Aboelsoud@jiadmotors.com​'),
('Majed Hassan Alzahrani', 'Parts Advisor', 'Jeddah', 'Nakheel', '555411406', 'Majed.Hassan@jiadmotors.com ​'),
('Omar Sahal Alattas', 'Workshop Controller', 'Madinah', 'Airport Road', '598030507', 'Omar.Alattas@jiadmotors.com​'),
('Mohamed Magdy Elsakar', 'Workshop Team Leader', 'Riyadh', 'Alsalih', '508976687', 'Mohammed.Elsakar@jiadmotors.com'),
('Yamen Habib Allah', 'Warranty Officer', 'Jeddah', 'Head Office', '549444900', 'Yamen.Habiballah@jiadmotors.com​'),
('Muhannad Alghamdi', 'Parts Advisor', 'Jeddah', 'Nakheel', '567437473', 'Muhannad.Algamdi@jiadmotors.com'),
('Sakib Ahmed', 'Parts Advisor', 'Riyadh', 'North', '507987583', 'Sakib.Ahmed@jiadmotors.com​'),
('Prince Kumar Singh', 'Inventory Controller', 'Jeddah', 'Head Office', '567087389', 'Prince.Kumar@jiadmotors.com​'),
('Mhmod Mhmd Amen', 'Service Advisor', 'Dammam', 'Khaldiah', '570712474', 'mahmoud.amin@jiadmotors.com'),
('Gamal Salah Abdelalim abdelgayed', 'Workshop Team Leader', 'Riyadh', 'North', '590966531', 'gamal.salah@jiadmotors.com'),
('Hamid Babekir Hamid Ahmed', 'Parts Advisor', 'Madinah', 'Airport Road', '504507290', 'hamid.babekir@jiadmotors.com'),
('John Pratheep John Ganesh', 'Parts Advisor', 'Jeddah', 'Nakheel', '541031505', 'John.Ganesh@jiadmotors.com​'),
('Alhussain Ali Hassan Ammurah', 'Service Advisor', 'Riyadh', 'Alsalih', '558281498', 'Alhussain.ammurah@jiadmotors.com'),
('Yoonas Babukottayil Kottayil', 'Warranty Officer', 'Riyadh', 'Alsalih', '540018902', 'Yoonas.Kottayil@jiadmotors.com'),
('Anmar Jaber Zogan', 'Parts Advisor', 'Jizan', 'Alsafa', '599961187', 'anmar.zogan@jiadmotors.com'),
('Adel Salem Bin Merdhah', 'Parts Advisor', 'Riyadh', 'Alsalih', '555046460', 'adel.merdhah@jiadmotors.com'),
('Mustafa Nasr Ibrahim', 'Technical Manager', 'Jeddah', 'Head Office', '597702321', 'mustafa.nasr@jiadmotors.com'),
('Arshad Aziz Mohammed', 'Workshop Controller', 'Riyadh', 'North', '530218660', 'arshad.mohammed@jiadmotors.com'),
('Munir Ahmed Muhammad Siddique', 'Parts Advisor', 'Riyadh', 'North', '599128458', 'Munir.Siddique@jiadmotors.com'),
('Jawaher Mohammed Alhashim', 'Parts Advisor', 'Dammam', 'Khaldiah', '598250656', 'Jawaher.Alhashim@jiadmotors.com'),
('Omar  Abdulhadi Kalantan', 'Service Advisor', 'Jeddah', 'Hiraa', '507004157', 'Omar.Kalantan@jiadmotors.com'),
('Mostafa Mohamed Sayed Elsayed', 'Service Advisor', 'Riyadh', 'North', '583326065', 'mostafa.elsayed@jiadmotors.com'),
('Mohamad Toufic Walid Mehio', 'Warranty Officer', 'Jeddah', 'Hiraa', '535294901', 'Mohammed.mehio@Jiadmotors.com'),
('Mohamed Ahmed Mohamed Eltantawy', 'Workshop Team Leader', 'Riyadh', 'Khurais', '538846231', 'mohamed.eltantawy@jiadmotors.com'),
('Mohammed Akbar Thodekkadan', 'Parts Advisor', 'Jeddah', 'Head Office', '565229410', 'Mohammed.Thodekkadan@jiadmotors.com'),
('Ali Mohammed Maki', 'Service Advisor', 'Jizan', 'Alsafa', '505733787', 'ali.maki@jiadmotors.com'),
('Hafiz Mohammed Sharif', 'Service Advisor', 'Jizan', 'Alsafa', '533559515', 'hafiz.sharif@jiadmotors.com'),
('Ahmed Elsayed Kamel Elsherif', 'Service advisor', 'Dammam', 'Khaldiah', '598347299', 'Ahmed.Elsherif@jiadmotors.com'),
('Abdellatif Ibrahim Abdellatif Ibrahim', 'Quality Controller', 'Riyadh', 'North', '546935336', 'Abdellatif.Ibrahim@jiadmotors.com'),
('Fahad Mohammed Almari', 'Parts Advisor', 'Riyadh', 'North', '566070550', 'fahad.almari@jiadmotors.com'),
('Musa Abdelrahman Mahgoub Mohamed Ahmed', 'Workshop Team Leader', 'Jizan', 'Alsafa', '558674114', 'Musa.Ahmed@jiadmotors.com​'),
('Mohammed Ridha Ibrahim Shuayrah', 'Service Advisor', 'Jeddah', 'Nakheel', '549883089', 'Mohammed.Shuayrah@jiadmotors.com'),
('Mostafa Mahmoud Kamel Ali', 'Service Advisor', 'Riyadh', 'North', '581605336', 'mostafa.ali@jiadmotors.com'),
('MOSTAFA IBRAHIM REDA ABOELNASR', 'Service Advisor', 'Riyadh', 'Alsalih', '544937274', 'Mostafa.Aboelnasr@jiadmotors.com'),
('Abdalla Hassan Hallousa', 'Service Advisor', 'Madinah', 'Airport Road', '507743759', 'Abdalla.Hallousa@jiadmotors.com'),
('MOSTAFA MAGDY MOHAMED MAHMOUD', 'Service Advisor', 'Jeddah', 'Hiraa', '509490052', 'Mostafa.Mahmoud@jiadmotors.com'),
('YOUSSEF AHMED ALY HAMED', 'Workshop Team Leader', 'Jeddah', 'Hiraa', '509053987', 'Youssef.Hamed@jiadmotors.com'),
('HESHAM MOHAMED TAHA ALI', 'Workshop Team Leader', 'Jeddah', 'Hiraa', '552390075', 'Hesham.Ali@jiadmotors.com'),
('HAMED TAREK HAMED ELHITAMY', 'Service Advisor', 'Abha', 'King Fahad', '546012346', 'Hamed.Elhitamy@jiadmotors.com'),
('AMMAR MOHAMED NASEF TAWFIK', 'Service Advisor', 'Riyadh', 'North', '540769651', 'Ammar.Tawfik@jiadmotors.com'),
('MOSTAFA HAITHAM MOSTAFA ELDEEB', 'Workshop Contoller', 'Jeddah', 'Nakheel', '544277142', 'Mostafa.Eldeeb@jiadmotors.com'),
('MOHAMMED IRFAN', 'Workshop Team Leader', 'Riyadh', 'Alsalih', '537821644', NULL),
('AHMAD NASEER MUHAMMAD AJLAN', 'Quality Controller', 'Jeddah', 'Nakheel', '547658692', 'Ahmed.Ajlan@jiadmotors.com​'),
('AHMAD ABDULLAH ATTIA', 'Workshop Team Leader', 'Riyadh', 'Alsalih', '548735838', 'Ahmad.Attia@jiadmotors.com'),
('AHMED HUSSEIN MOHAMED ALY', 'Workshop Team Leader', 'Jeddah', 'Hiraa', '548168809', 'Ahmed.Aly@jiadmotors.com'),
('KARIM MOHAMED OSAMA AMIN', 'Warranty Officer', 'Riyadh', 'North', '544989559', 'Karim.Amin@jiadmotors.com'),
('AMR ADEL MOSTAFA ABDELHAFEZ', 'Workshop Team Leader', 'Riyadh', 'North', '544732781', 'Amr.Abdelhafez@jiadmotors.com'),
('Mohammed Ahmed Gallab', 'Workshop Contoller', 'Jizan', 'Alsafa', '545487056', 'mohammed.gallab@jiadmotors.com'),
('Saad Sarmini', 'Wholesale Parts Executive', 'Jeddah', 'Head Office', '581109080', 'saad.sarmini@jiadmotors.com'),
('Saeed Rashed Alahmari', 'Service Advisor', 'Abha', 'King Fahad', '533427202', 'saeed.alahmari@jiadmotors.com'),
('Yousef Mohammed Alqhtani', 'Receptionist', 'Abha', 'King Fahad', '598992211', 'yousef.alqhtani@jiadmotors.com'),
('Ahmed Naef Alharbi', 'Service Advisor', 'Qassim', 'Buraidah', '545094335', 'Ahmed.Naef@jiadmotors.com'),
('Mohammed Abdulaziz Albadia', 'Service Advisor', 'Riyadh', 'Khurais', '544022525', 'mohammed.albadia@jiadmotors.com'),
('Abdulrahman Mohammed Haqawi', 'Parts Advisor', 'Abha', 'King Fahad', '544004979', 'abdulrahman.haqawi@jiadmotors.com'),
('Ahmed Mohammed Bahifth Allah', 'Parts Advisor', 'Riyadh', 'Alsalih', '555466525', 'ahmed.bahifth@jiadmotors.com'),
('Ahmed Mohammed Alamoodi', 'Quality Controller', 'Jeddah', 'Nakheel', '548716673', 'ahmed.alamoodi@jiadmotors.com'),
('Mohamed Atef Ahmed', 'Diagnostics Technician', 'Riyadh', 'North', '535206416', NULL),
('Ahmed Ashraf Khalil', 'Workshop Team Leader', 'Jeddah', 'Hiraa', '530903136', 'ahmed.khalil@jiadmotors.com'),
('Mostafa Magdy Aboshahba', 'Workshop Team Leader', 'Riyadh', 'North', '530781838', 'mostafa.aboshahba@jiadmotors.com'),
('Amirah Abdulaziz Saleh Alghamdi', 'Receptionist', 'Jeddah', 'Hiraa', '552853628', 'Ameera.Alghamdi@jiadmotors.com'),
('Ali Mohammed Ali Alahmri', 'Parts Advisor', 'Jeddah', 'Hiraa', '566025247', 'Ali.Alahmri@jiadmotors.com'),
('Muhannad Faisal Mohamed Almadani', 'Parts Advisor', 'Riyadh', 'Khurais', '557091100', 'Muhannad.Almadani@jiadmotors.com'),
('Salem Ali Hasan Alfahimi', 'Parts Advisor', 'Jeddah', 'Hiraa', '559622284', 'Salem.Alfahimi@jiadmotors.com'),
('Mohammed Saeed Abdullah Alabd', 'Parts Advisor', 'Abha', 'King Fahad', '580322259', 'mohammed.alabed@jiadmotors.com'),
('Yousef Alhazmi', 'Repair Technician', 'Jeddah', 'Hiraa', '567731416', NULL),
('Javed Alam MD Moosa', 'Repair Technician', 'Riyadh', 'Alsalih', '557882612', NULL),
('Abdulbari Abbas', 'Repair Technician', 'Jeddah', 'Nakheel', '502066833', NULL),
('Sonny Zabala', 'Repair Technician', 'Jeddah', 'Hiraa', '534054379', NULL),
('Abdullah Abdelsalam', 'Repair Technician', 'Jeddah', 'Hiraa', '565530415', NULL),
('Mohammed Mutlak', 'Repair Technician', 'Jeddah', 'Hiraa', '544245597', NULL),
('MUDASSAR CONTRACTOR', 'Repair Technician', 'Madinah', 'Airport Road', '554011803', NULL),
('PRASANTH JAGADEESWARAN', 'Repair Technician', 'Riyadh', 'Alsalih', '597383014', NULL),
('SAMEEL NANGALATH PUTHIYAPURAYIL', 'Repair Technician', 'Riyadh', 'Alsalih', '556058759', NULL),
('MIDHUN PLAVUMKAL CHACKO', 'Repair Technician', 'Jeddah', 'Hiraa', '554285695', NULL),
('SANDESH SHETTY', 'Repair Technician', 'Jeddah', 'Hiraa', '553404288', NULL),
('SAYANTH UCHUMMAL', 'Repair Technician', 'Jeddah', 'Hiraa', '555839225', NULL),
('AKHIL ANTONY VARGHESE', 'Repair Technician', 'Dammam', 'Khaldiah', '538776154', NULL),
('ARUN PANDARIKKAL', 'Repair Technician', 'Dammam', 'Khaldiah', '538776385', NULL),
('JISHNU PAYAROLITHAZHA KUNIYIL', 'Repair Technician', 'Dammam', 'Khaldiah', '538779925', NULL),
('JITHIN THOOMBAYIL RAJ', 'Repair Technician', 'Dammam', 'Khaldiah', '552261267', NULL),
('MUHAMMED HASEEN V MUHAMMED ALI', 'Repair Technician', 'Dammam', 'Khaldiah', '563564260', NULL),
('YOGESH PATIL', 'Repair Technician', 'Dammam', 'Khaldiah', '553294015', NULL),
('RAKSHITH BEEDU', 'Repair Technician', 'Jeddah', 'Madinah Road', '552954606', NULL),
('Julito Competente', 'Repair Technician', 'Riyadh', 'North', '537065386', NULL),
('Muhammed Shereef Ambukkadan', 'Repair Technician', 'Madinah', 'Airport Road', '546980628', NULL),
('Shamjith Valakkada', 'Repair Technician', 'Riyadh', 'Alsalih', '537010507', NULL),
('Anoop Cheenikottil', 'Repair Technician', 'Riyadh', 'Alsalih', '506541997', NULL),
('Shailesh Sathisha Poojary', 'Repair Technician', 'Riyadh', 'Alsalih', '537313742', NULL),
('Tamer Moustafa Elnady', 'Aftersales Director', 'Jeddah', 'Head Office', '532582035', 'tamer.elnady@jiadmotors.com'),
('Sujesh Koriyattil', 'Repair Technician', 'Riyadh', 'Alsalih', '535491371', NULL),
('Jose Rison', 'Repair Technician', 'Riyadh', 'Alsalih', '532947487', NULL),
('Vivek Muraleedharan', 'Repair Technician', 'Riyadh', 'Alsalih', '535442821', NULL),
('Vasantha Chavadi', 'Repair Technician', 'Jeddah', 'Hiraa', '554494583', NULL),
('Shuaib Bdrudeen Bdrudeen A', 'Warranty Officer', 'Jeddah', 'Head Office', '569342275', 'Shuaib.Badarudeen@jiadmotors.com​'),
('MOHAMED SHEMEEM THOTTIYIL', 'Repair Technician', 'Jeddah', 'Hiraa', '567310407', NULL),
('ATHUL KATTERI', 'Repair Technician', 'Jeddah', 'Hiraa', '569664243', NULL),
('PAVAN NAGABHU SHAN SHIVAMOGGA', 'Repair Technician', 'Dammam', 'Khaldiah', '536364615', NULL),
('AJEESH CHUKKAMKONAM ARUMUGHAN', 'Repair Technician', 'Abha', 'King Fahad', '501072045', NULL),
('MUHAMMED ALTHAF KAKKATTUCHALI', 'Repair Technician', 'Jeddah', 'Madinah Road', '559414789', NULL),
('Waleed Aboubakr Ibrahim', 'Repair Technician', 'Jeddah', 'Hiraa', '534648921', NULL),
('Yaser Abdulrahman Damen', 'Repair Technician', 'Madinah', 'Airport Road', '538327985', NULL),
('Fahad Khan Afsar', 'Repair Technician', 'Jeddah', 'Hiraa', '505831449', NULL),
('MUSAMMIL MULLANTAKATH', 'Repair Technician', 'Riyadh', 'Khurais', '507393463', NULL),
('VIGNESHA VASUDEVA', 'Repair Technician', 'Riyadh', 'Khurais', '556736195', NULL),
('Turki Sunari', 'Repair Technician', 'Jeddah', 'Nakheel', '551920747', NULL),
('MUHAMMED AFTHAB PAIKKATTU CHALI', 'Repair Technician', 'Jizan', 'Alsafa', '538378462', NULL),
('MUHAMMED NASEEF MELEDATH', 'Repair Technician', 'Jizan', 'Alsafa', '538817261', NULL),
('ANTONY JOY', 'Repair Technician', 'Jizan', 'Alsafa', '538323059', NULL),
('BINU VARAPPURATHU BABUKUTTAN', 'Repair Technician', 'Jizan', 'Alsafa', '503115743', NULL),
('BIBIN PRASAD', 'Repair Technician', 'Jizan', 'Alsafa', '550262590', NULL),
('DHEERAJ KALATHUPURATH RAJAN', 'Repair Technician', 'Abha', 'King Fahad', '535414183', NULL),
('NIKHILRAJ PERUMTHODI', 'Repair Technician', 'Abha', 'King Fahad', '538055942', NULL),
('SHIJIN PLAKANDIYIL', 'Repair Technician', 'Abha', 'King Fahad', '538342142', NULL),
('ELDHOSE PULICHOTTIL PAULOSE', 'Repair Technician', 'Abha', 'King Fahad', '533669182', NULL),
('SMIJITH KAPLINGATTU SUBRAMANIAN', 'Repair Technician', 'Jeddah', 'Nakheel', '552064232', NULL),
('HARIKRISHNAN MAPPILAKUNNEL SAJI', 'Repair Technician', 'Jeddah', 'Nakheel', '533051640', NULL),
('DHILIBAN DEENADAYALAN', 'Repair Technician', 'Jeddah', 'Nakheel', '537487517', NULL),
('BIPIN CHERUPARAMBIL SEBASTIAN', 'Repair Technician', 'Jeddah', 'Nakheel', '553794998', NULL),
('AJO SHAIJAN', 'Repair Technician', 'Jeddah', 'Nakheel', '533942411', NULL),
('SHAJEER ABDUL SALEEM', 'Repair Technician', 'Riyadh', 'North', '538336847', NULL),
('SEMEER NELLIKKAL', 'Repair Technician', 'Riyadh', 'North', '539572520', NULL),
('Wilbert Combo Margallo', 'Repair Technician', 'Riyadh', 'North', '533983959', NULL),
('Rakan Saad Almalki', 'Repair Technician', 'Jeddah', 'Nakheel', '581481951', NULL),
('Mohammed Ethasham Mohammed Irfan', 'Repair Technician', 'Jeddah', 'Hiraa', '567112638', NULL),
('Mahamat Abdallah Dogo Ali', 'Repair Technician', 'Jeddah', 'Nakheel', '541883001', NULL),
('Rochdi Mohamed Ben Romdhane', 'Repair Technician', 'Madinah', 'Airport Road', '565254729', NULL),
('Arnold Asuncion Adiaz', 'Repair Technician', 'Jeddah', 'Nakheel', '563101751', NULL),
('BILAL AHMED KHALID AMIN', 'Repair Technician', 'Madinah', 'Airport Road', '574337078', NULL),
('BELAL MAHMOUD IBRAHIM KHALIL', 'Repair Technician', 'Jizan', 'Alsafa', '555473161', NULL),
('MAHMOUD FAWZY ABDELMOTELEB ELSAYED', 'Repair Technician', 'Riyadh', 'Alsalih', '561636221', NULL),
('ANSAR BABU', 'Repair Technician', 'Madinah', 'Airport Road', '553576103', NULL),
('NAGARAJ PRAKASH JADHAV', 'Repair Technician', 'Riyadh', 'Alsalih', '556901726', NULL),
('PRAMOD MOORKATHODI', 'Repair Technician', 'Riyadh', 'Alsalih', '534913372', NULL),
('SANOOP POOKKULAYAN', 'Repair Technician', 'Riyadh', 'Alsalih', '559624771', NULL),
('UZER PASHA', 'Repair Technician', 'Riyadh', 'Alsalih', '552954462', NULL),
('KRISHNADAS THALAKKATTE', 'Repair Technician', 'Riyadh', 'Alsalih', '573042726', NULL),
('JAMSHAD ANKALAM', 'Repair Technician', 'Qassim', 'Buraidah', '537801716', NULL),
('LIJIN MANNOORKKARA', 'Repair Technician', 'Qassim', 'Buraidah', '556538101', NULL),
('RANJITH KUNNATHAM PARAMBIL CHAMI', 'Repair Technician', 'Qassim', 'Buraidah', '559601721', NULL),
('AMEY RAMAKANT DESSAI', 'Repair Technician', 'Jeddah', 'Hiraa', '552587900', NULL),
('KAILAS CHEMBRA VELAYUDHAN', 'Repair Technician', 'Jeddah', 'Hiraa', '555872573', NULL),
('MANISH MANOHAR GURAV', 'Repair Technician', 'Jeddah', 'Hiraa', '537825171', NULL),
('MURUGESAN KUMARASAMY', 'Repair Technician', 'Jeddah', 'Hiraa', '555864788', NULL),
('AMAL CHALIL POTTAMMAL', 'Repair Technician', 'Dammam', 'Khaldiah', '557440615', NULL),
('NIKHIL THESSERY RAJAN', 'Repair Technician', 'Dammam', 'Khaldiah', '554236788', NULL),
('SUBRAHMANYA KOTI NAIK', 'Repair Technician', 'Dammam', 'Khaldiah', '553809498', NULL),
('THILAK SUNDARA POOJARY', 'Repair Technician', 'Dammam', 'Khaldiah', '558543025', NULL),
('MANICKAM MUTHIYA', 'Repair Technician', 'Dammam', 'Khaldiah', '511415694', NULL),
('SATHISHA GOWDA', 'Repair Technician', 'Dammam', 'Khaldiah', '510306982', NULL),
('RAMITH BILLAVA SHESHAPPA', 'Repair Technician', 'Dammam', 'Khaldiah', '511451608', NULL),
('ELDHOSE JOLLY', 'Repair Technician', 'Riyadh', 'Khurais', '553908011', NULL),
('AKASH SANTHOSH', 'Repair Technician', 'Riyadh', 'Khurais', '571011064', NULL),
('JOYAL VARGHESE', 'Repair Technician', 'Riyadh', 'Khurais', '508114895', NULL),
('AKSHAY SOMAN VALLIKKOL', 'Repair Technician', 'Riyadh', 'Khurais', '573059754', NULL),
('Abdullah Bazyad', 'Repair Technician', 'Jeddah', 'Madinah Road', '553419928', 'abdullah.bazyad@jiadmotors.com'),
('NIZAMUDDIN ISMAIL KHOPATKAR', 'Repair Technician', 'Jeddah', 'Madinah Road', '555787694', NULL),
('AKHIL VAKAYIL MURALI', 'Repair Technician', 'Riyadh', 'North', '535562186', NULL),
('DON KOZHIKKADAN LONAPPAN', 'Repair Technician', 'Riyadh', 'North', '507981312', NULL),
('DEEPAK MANUKKADAN SURENDRAN', 'Repair Technician', 'Riyadh', 'North', '536002178', NULL),
('SAJEESH KALARI PARAMBATH', 'Repair Technician', 'Riyadh', 'North', '550251748', NULL),
('ABHINAV KOOLI', 'Repair Technician', 'Riyadh', 'North', '556231912', NULL),
('NIKHIL PETER', 'Repair Technician', 'Riyadh', 'North', '556410817', NULL),
('MAHBOOB MIYAN', 'Repair Technician', 'Riyadh', 'North', '556275622', NULL),
('Adnan Bin Mahfooz', 'Repair Technician', 'Riyadh', 'North', '509512187', NULL),
('JOJO PORATHUR JOHNSON', 'Repair Technician', 'Riyadh', 'Alsalih', '509383593', NULL),
('MANIKANDAN MOHANAN', 'Repair Technician', 'Abha', 'King Fahad', '538409229', NULL),
('ANSHAD MATTUVAYAL', 'Repair Technician', 'Jeddah', 'Nakheel', '538324812', NULL),
('AHAMED SAJID ARANGATHIL', 'Repair Technician', 'Jeddah', 'Nakheel', '538418438', NULL),
('VISHNU SOMAN', 'Repair Technician', 'Jeddah', 'Nakheel', '532124278', NULL),
('Ghayoor Akhtar Baluchi', 'Repair Technician', 'Jeddah', 'Nakheel', '563958353', NULL),
('Mohammed Ahmed Ghassan Alothman', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '533008136', NULL),
('Hassan Yasir Abdullah Alsinan', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '542907664', NULL),
('Fahad Waheed Mohammed Rasheed Saad', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '580307255', NULL),
('Abdulaziz Abdullah Dhaifullah Alqurashi', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '544482835', NULL),
('Hamzah Emad Mohammed Kashmiri', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '549636470', NULL),
('Ibrahim Ahmed Abdullah Jaafari', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '581130535', NULL),
('Mohammed Ahmed Ali Athlawi', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '552726178', NULL),
('Rayan Mohammed Ahmed Mohammed', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '567170675', NULL),
('Abdullah Sami Abdullah Albahrani', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '580254639', NULL),
('Abbas Helal Hasan Alnazgah', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '566434594', NULL),
('Abdulhadi Shaker Mohamed Alshehri', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '531828027', NULL),
('Marwan Mohammed Jaafr Alrashdi', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '566195356', NULL),
('Saleh Khalid Saleh Alfalaj', 'Mechanic Trainee', 'Jeddah', 'Hiraa', '508309112', NULL),
('Junaid Ahmed Khan', 'Repair Technician', 'Riyadh', 'North', '597789647', NULL),
('ABDULLAH ARSHAD  MUHAMMAD  QURESHI', 'Repair Technician', 'Jeddah', 'Madinah Road', '547173730', NULL),
('Fayaz Sayed', 'Parts Picker', 'Jeddah', 'Hiraa', '542755437', NULL),
('Khalid Salih Osman', 'Parts Picker', 'Qassim', 'Buraidah', '590407264', NULL),
('Afsar Shah', 'Parts Picker', 'Riyadh', 'Alsalih', '509637257', NULL),
('Zakir Bukhsh', 'Parts Picker', 'Riyadh', 'Alsalih', '599696489', NULL),
('Shoaib khan', 'Parts Picker', 'Dammam', 'Khaldiah', '597169190', NULL),
('ABDULLAH ISMAIL SHAHNUR', 'Parts Picker', 'Jeddah', 'Hiraa', '550528790', NULL),
('Adel Adres', 'Parts Picker', 'Riyadh', 'Alsalih', '505347088', NULL),
('AhmadMahboob Mahboobulhaq', 'Parts Picker', 'Madinah', 'Airport Road', '508842757', NULL),
('Ali Masoud Aldahbali', 'Parts Picker', 'Abha', 'King Fahad', '508711672', NULL),
('Ibrahim Tahir Adbraman', 'Parts Picker', 'Jeddah', 'Nakheel', '557876795', NULL),
('Rubel Miah Hanif Miah', 'Parts Picker', 'Riyadh', 'North', '558410340', NULL),
('Hozaifa Mohammed Ali Idris', 'Parts Picker', 'Riyadh', 'North', '582719761', NULL),
('Al-Amin Abdul Gani - Huwlader', 'Parts Picker', 'Jeddah', 'Nakheel', '552080775', NULL),
('Yahya Mohammed Bakheet', 'Parts Picker', 'Jizan', 'Alsafa', '500353469', NULL),
('Hasem Md Abulkalam', 'Parts Picker', 'Madinah', 'Airport Road', '593024368', NULL),
('Alhussien Sireur Ahmedden', 'Parts Picker', 'Riyadh', 'Khurais', '552376979', NULL),
('Muhammad Bilalamjad', 'Parts Picker', 'Abha', 'King Fahad', '598292642', NULL),
('Omor Faruk', 'Parts Picker', 'Jeddah', 'Hiraa', '535136344', NULL),
('Muhammad Muzammal Muhammad Saqib', 'Parts Picker', 'Riyadh', 'Alsalih', '592953280', NULL),
('Turki Khinab', 'Driver', 'Jeddah', 'Hiraa', '566227090', NULL),
('Mahmoud Hamid', 'Driver', 'Riyadh', 'Alsalih', '577494216', NULL),
('Mohamednoor ALi', 'Driver', 'Riyadh', 'Alsalih', '500468224', NULL),
('Haitham Ali', 'Driver', 'Dammam', 'Khaldiah', '532617780', NULL),
('Bakri Dirar', 'Driver', 'Jeddah', 'Nakheel', '563020693', NULL),
('Ali Salih Diwaed', 'Driver', 'Madinah', 'Airport Road', '570373477', NULL),
('Hashim Osman Hamid Ali', 'Driver', 'Jizan', 'Alsafa', '561849075', NULL),
('Ahmed Osman Ahmed Ali', 'Driver', 'Riyadh', 'North', '594869746', NULL),
('Mosaab Mohamed Jemea Mahmoud', 'Driver', 'Riyadh', 'North', '530466242', NULL),
('Omer Derar Mohammed', 'Driver', 'Riyadh', 'Alsalih', '540538349', NULL),
('Mohammed Shoei Helal', 'Driver', 'Jeddah', 'Hiraa', '540874980', NULL),
('Mahammadazam Mahammadbuata', 'Driver', 'Jeddah', 'Hiraa', '580233953', NULL),
('Abdullah Abdulaziz Ahmed', 'Driver', 'Abha', 'King Fahad', '581447470', NULL),
('Alamin Suleman Mhmoud', 'Driver', 'Dammam', 'Khaldiah', '549680832', NULL),
('Mouid Maziad Alosman', 'Service Advisor', 'Jeddah', 'Hiraa', '505434367', NULL),
('Jamal Elsnari', 'Repair Technician', 'Jeddah', 'Nakheel', '564761907', NULL),
('Ali Nasser Asiri', 'Repair Technician', 'Jeddah', 'Hiraa', '563603138', NULL);
