-- Auto-generated from Employees.xlsx — do not hand-edit, regenerate instead.
truncate table app_users restart identity;
insert into app_users (name, email, password, role, employee_branch, demo_branch_code, title) values
('Khaled Alarrad', 'khaled.alarrad@jiadmotors.com', 'Khaled@123', 'manager', 'King Fahad', NULL, 'Service Manager'),
('Ahmed Mufeed Mahmoud', 'Ahmed.Mahmod@jiadmotors.com', 'Ahmed@123', 'manager', 'Head Office', 'JED-01', 'Head of service'),
('Ashwaq Alanazi', 'ashwaq.alenezi@jiadmotors.com', 'Ashwaq@123', 'staff', 'Head Office', 'JED-01', 'Customer Complaints Supervisor'),
('Adil Saleh Almakhlafi', 'adil.almakhlafi@jiadmotors.com', 'Adil@123', 'manager', 'Khaldiah', 'DMM-01', 'Service Manager'),
('Salih Ismail Elsayed', 'saleh.ismail@jiadmotors.com', 'Salih@123', 'manager', 'Airport Road', NULL, 'Service Manager'),
('Amaal Algrigri', 'amal.hamdan@jiadmotors.com', 'Amaal@123', 'staff', 'Head Office', 'JED-01', 'Customer Complaints Executive'),
('Khaled Alghamdi', 'Khaled.Alghamdy@jiadmotors.com', 'Khaled@123', 'staff', 'Head Office', 'JED-01', 'Customer Complaints Executive'),
('Mehad Aljehani', 'Mehad.Aljehani@jiadmotors.com​', 'Mehad@123', 'staff', 'Head Office', 'JED-01', 'Customer Complaints Executive'),
('Ahmed Gomaa Sayed Mohammed', 'ahmed.gomaa@jiadmotors.com', 'Ahmed@123', 'manager', 'Hiraa', 'JED-01', 'Service Manager'),
('Ahmed Nader Abdelaziz', 'ahmed.nader@jiadmotors.com', 'Ahmed@123', 'manager', 'North', 'RUH-01', 'Service Manager'),
('ELHASSAN BELKASMI', 'elhassan.belkasmi@jiadmotors.com', 'Elhassan@123', 'manager', 'Head Office', 'JED-01', 'Technical Manager'),
('Mohammed Osama Abu Ahmad', 'Mohammed.osama@jiadmotors.com', 'Mohammed@123', 'manager', 'Head Office', 'JED-01', 'Parts Manager'),
('Ahmed Ibrahim Tayel', 'ahmed.tayel@jiadmotors.com', 'Ahmed@123', 'manager', 'Nakheel', 'JED-01', 'Service Manager'),
('Fahd Saleh Ahmed Omar', 'Fahad.Omar@jiadmotors.com', 'Fahd@123', 'staff', 'North', 'RUH-01', 'Wholesale Parts Supervisor'),
('Muhammad Adam Muhammad Siddiq', 'Mohammed.Siddiq@jiadmotors.com', 'Muhammad@123', 'staff', 'Hiraa', 'JED-01', 'Parts Supervisor'),
('Ahmed Hablil', 'Ahmed.Hablil@jiadmotors.com', 'Ahmed@123', 'staff', 'Madinah Road', 'JED-01', 'Workshop Supervisor'),
('Mohammad Babgi', 'Mohammad.Babqi@jiadmotors.com', 'Mohammad@123', 'staff', 'Nakheel', 'JED-01', 'Workshop Supervisor'),
('Rami Kamli', 'Rami.Kamli@jiadmotors.com', 'Rami@123', 'staff', 'Alsafa', NULL, 'Parts Supervisor'),
('Ahmed Mustafa Ahmed', 'Ahmad.Mustafa@jiadmotors.com', 'Ahmed@123', 'manager', 'Head Office', 'JED-01', 'Customer Experience Manager'),
('Anad Alsayyali', 'anad.alsayyali@jiadmotors.com', 'Anad@123', 'staff', 'Hiraa', 'JED-01', 'Service Supervisor'),
('Hussain Alhumaidi', 'hussain.alhumaidi@jiadmotors.com', 'Hussain@123', 'staff', 'Khaldiah', 'DMM-01', 'Parts Supervisor'),
('Sulaman Paracha', 'Sulaman.Paracha@jiadmotors.com', 'Sulaman@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Supervisor'),
('Adam Tarek Makboul', 'adam.makboul@jiadmotors.com', 'Adam@123', 'staff', 'Khaldiah', 'DMM-01', 'Service Supervisor'),
('Moaaz Shabaan Elsayed', 'Moaaz.Shabaan@jiadmotors.com', 'Moaaz@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Supervisor'),
('Irfan Syed Ahmed', 'Irfan.Ahmed@jiadmotors.com', 'Irfan@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Supervisor'),
('Zaki Alsheikh', 'Zaki.Alsheikh@jiadmotors.com', 'Zaki@123', 'staff', 'Head Office', 'JED-01', 'Trainer'),
('Osman Ahmed', 'osman.ahmed@jiadmotors.com', 'Osman@123', 'staff', 'Alsalih', 'RUH-01', 'Service Supervisor'),
('Karim Hussein Abdelwahab Mohamed', 'Kareem.Mohammed@jiadmotors.com​', 'Karim@123', 'staff', 'Airport Road', NULL, 'Workshop Supervisor'),
('Ahmad Hamdani', 'ahmad.hamdani@jiadmotors.com', 'Ahmad@123', 'admin', 'Hiraa', 'JED-01', 'Warranty Officer'),
('Ansar Bawajeeh', 'Ansar.Bawajeeh@jiadmotors.com', 'Ansar@123', 'staff', 'Head Office', 'JED-01', 'Warranty Officer'),
('Ibrahim Abdalla Ibrahim Mohamedali', 'ibrahim.mohamed@jiadmotors.com', 'Ibrahim@123', 'staff', 'North', 'RUH-01', 'Parts Supervisor'),
('Younes Mohamed Younes Elmasry', 'younes.elmasryi@jiadmotors.com', 'Younes@123', 'staff', 'Khaldiah', 'DMM-01', 'Workshop Supervisor'),
('Sabeel Ismail Majal', 'Sabeel.Ismail@jiadmotors.com', 'Sabeel@123', 'staff', 'Hiraa', 'JED-01', 'Parts Supervisor'),
('Muhammad Waqar Amin', 'muhammad.amin@jiadmotors.com', 'Muhammad@123', 'staff', 'Head Office', 'JED-01', 'Parts Inventory Supervisor'),
('Mohammed Amin Bakheribah', 'mohammed.bakheribah@jiadmotors.com', 'Mohammed@123', 'staff', 'North', 'RUH-01', 'Service Supervisor'),
('Basmah Almutairi', 'Basmah.Almutairi@jiadmotors.com', 'Basmah@123', 'advisor', 'Madinah Road', 'JED-01', 'Service Advisor'),
('Rayan Alyazidi', 'Rayan.Alyazidi@jiadmotors.com', 'Rayan@123', 'staff', 'Hiraa', 'JED-01', 'Parts Advisor'),
('Mehdi Binabicha', 'Mehdi.Binabicha@jiadmotors.com', 'Mehdi@123', 'staff', 'Khaldiah', 'DMM-01', 'Warranty Officer'),
('Khalid Almatrafi', 'khalid.almatrfi@jiadmotors.com', 'Khalid@123', 'advisor', 'Madinah Road', 'JED-01', 'Service Advisor'),
('Abdullah Alammar', 'Abdullah.Alammar@jiadmotors.com', 'Abdullah@123', 'staff', 'Alsalih', 'RUH-01', 'Receptionist'),
('Yahya Alshowiki', 'yahya.alshowiki@jiadmotors.com', 'Yahya@123', 'staff', 'Khaldiah', 'DMM-01', 'Quality Controller'),
('Mohammed Alkhalifah', 'Mohammed.Alkhalifah@jiadmotors.com', 'Mohammed@123', 'advisor', 'Khaldiah', 'DMM-01', 'Service Advisor'),
('Ghada Alharbi', 'ghadah.alharbi@jiadmotors.com', 'Ghada@123', 'staff', 'Hiraa', 'JED-01', 'Parts Advisor'),
('Sultan Almalki', 'Sultan.Almalki@jiadmotors.com', 'Sultan@123', 'staff', 'Nakheel', 'JED-01', 'Receptionist'),
('Parawaiz Syed', 'Parwiz.Syed@jiadmotors.com', 'Parawaiz@123', 'staff', 'King Fahad', NULL, 'Workshop Controller'),
('Bader Alanazi', 'Bader.Alanazi@jiadmotors.com', 'Bader@123', 'staff', 'Khurais', 'RUH-01', 'Parts Advisor'),
('Ahmed Wali Shutaifi', 'Ahmed.Shutaifi@jiadmotors.com', 'Ahmed@123', 'staff', 'Khaldiah', 'DMM-01', 'Parts Advisor'),
('Alhasan Alhunaiti', 'Alhasan.Alhunaiti@jiadmotors.com', 'Alhasan@123', 'staff', 'Head Office', 'JED-01', 'Warranty Supervisor'),
('Vinay Kaul', 'Vinay.Kaul@jiadmotors.com', 'Vinay@123', 'manager', 'Head Office', 'JED-01', 'Head of Parts'),
('Mohammed Makram', 'Mohammed.Makram@jiadmotors.com', 'Mohammed@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Advisor'),
('AKANEETH SURENDRAN', 'Akaneeth.Surendran@jiadmotors.com', 'Akaneeth@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Controller'),
('IMRAN JAFARKHAN PATHAN', 'imran.jafarkhan.pathan@jiadmotors.com', 'Imran@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Controller'),
('SURIYAN RAMU', 'suriyan.ramu@jiadmotors.com', 'Suriyan@123', 'staff', 'Khaldiah', 'DMM-01', 'Workshop Controller'),
('Muath Alkabsi', 'Muath.Alkabsi@jiadmotors.com', 'Muath@123', 'staff', 'Head Office', 'JED-01', 'Data Analyst'),
('Khurram Shahzad', 'khurram.shahzad@jiadmotors.com', 'Khurram@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Team Leader'),
('Hussain Saleh Hasan', 'hussain.hasan@jiadmotors.com', 'Hussain@123', 'staff', 'Khaldiah', 'DMM-01', 'Parts Advisor'),
('Essa Alshamekh', 'Essa.alshamekh@jiadmotors.com', 'Essa@123', 'staff', 'Buraidah', NULL, 'Parts Advisor'),
('Hamzah Akmubarak', 'hamzah.almubarak@jiadmotors.com', 'Hamzah@123', 'staff', 'Khaldiah', 'DMM-01', 'Receptionist'),
('Khalid Saleh Albloshi', 'Khaled.Albloshi@jiadmotors.com', 'Khalid@123', 'advisor', 'Airport Road', NULL, 'Service Advisor'),
('Farhan Ansari', 'farhan.ansari@jiadmotors.com', 'Farhan@123', 'staff', 'Head Office', 'JED-01', 'Parts Advisor'),
('Amr Youssri Elsherbini', 'amr.elsherbini@jiadmotors.com', 'Amr@123', 'advisor', 'Hiraa', 'JED-01', 'Service Advisor'),
('Omar Gad Atta Aboelsoud', 'Omar.Aboelsoud@jiadmotors.com​', 'Omar@123', 'advisor', 'Alsalih', 'RUH-01', 'Service Advisor'),
('Majed Hassan Alzahrani', 'Majed.Hassan@jiadmotors.com ​', 'Majed@123', 'staff', 'Nakheel', 'JED-01', 'Parts Advisor'),
('Omar Sahal Alattas', 'Omar.Alattas@jiadmotors.com​', 'Omar@123', 'staff', 'Airport Road', NULL, 'Workshop Controller'),
('Mohamed Magdy Elsakar', 'Mohammed.Elsakar@jiadmotors.com', 'Mohamed@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Team Leader'),
('Yamen Habib Allah', 'Yamen.Habiballah@jiadmotors.com​', 'Yamen@123', 'staff', 'Head Office', 'JED-01', 'Warranty Officer'),
('Muhannad Alghamdi', 'Muhannad.Algamdi@jiadmotors.com', 'Muhannad@123', 'staff', 'Nakheel', 'JED-01', 'Parts Advisor'),
('Sakib Ahmed', 'Sakib.Ahmed@jiadmotors.com​', 'Sakib@123', 'staff', 'North', 'RUH-01', 'Parts Advisor'),
('Prince Kumar Singh', 'Prince.Kumar@jiadmotors.com​', 'Prince@123', 'staff', 'Head Office', 'JED-01', 'Inventory Controller'),
('Mhmod Mhmd Amen', 'mahmoud.amin@jiadmotors.com', 'Mhmod@123', 'advisor', 'Khaldiah', 'DMM-01', 'Service Advisor'),
('Gamal Salah Abdelalim abdelgayed', 'gamal.salah@jiadmotors.com', 'Gamal@123', 'staff', 'North', 'RUH-01', 'Workshop Team Leader'),
('Hamid Babekir Hamid Ahmed', 'hamid.babekir@jiadmotors.com', 'Hamid@123', 'staff', 'Airport Road', NULL, 'Parts Advisor'),
('John Pratheep John Ganesh', 'John.Ganesh@jiadmotors.com​', 'John@123', 'staff', 'Nakheel', 'JED-01', 'Parts Advisor'),
('Alhussain Ali Hassan Ammurah', 'Alhussain.ammurah@jiadmotors.com', 'Alhussain@123', 'advisor', 'Alsalih', 'RUH-01', 'Service Advisor'),
('Yoonas Babukottayil Kottayil', 'Yoonas.Kottayil@jiadmotors.com', 'Yoonas@123', 'staff', 'Alsalih', 'RUH-01', 'Warranty Officer'),
('Anmar Jaber Zogan', 'anmar.zogan@jiadmotors.com', 'Anmar@123', 'staff', 'Alsafa', NULL, 'Parts Advisor'),
('Adel Salem Bin Merdhah', 'adel.merdhah@jiadmotors.com', 'Adel@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Advisor'),
('Mustafa Nasr Ibrahim', 'mustafa.nasr@jiadmotors.com', 'Mustafa@123', 'manager', 'Head Office', 'JED-01', 'Technical Manager'),
('Arshad Aziz Mohammed', 'arshad.mohammed@jiadmotors.com', 'Arshad@123', 'staff', 'North', 'RUH-01', 'Workshop Controller'),
('Munir Ahmed Muhammad Siddique', 'Munir.Siddique@jiadmotors.com', 'Munir@123', 'staff', 'North', 'RUH-01', 'Parts Advisor'),
('Jawaher Mohammed Alhashim', 'Jawaher.Alhashim@jiadmotors.com', 'Jawaher@123', 'staff', 'Khaldiah', 'DMM-01', 'Parts Advisor'),
('Omar  Abdulhadi Kalantan', 'Omar.Kalantan@jiadmotors.com', 'Omar@123', 'advisor', 'Hiraa', 'JED-01', 'Service Advisor'),
('Mostafa Mohamed Sayed Elsayed', 'mostafa.elsayed@jiadmotors.com', 'Mostafa@123', 'advisor', 'North', 'RUH-01', 'Service Advisor'),
('Mohamad Toufic Walid Mehio', 'Mohammed.mehio@Jiadmotors.com', 'Mohamad@123', 'staff', 'Hiraa', 'JED-01', 'Warranty Officer'),
('Mohamed Ahmed Mohamed Eltantawy', 'mohamed.eltantawy@jiadmotors.com', 'Mohamed@123', 'staff', 'Khurais', 'RUH-01', 'Workshop Team Leader'),
('Mohammed Akbar Thodekkadan', 'Mohammed.Thodekkadan@jiadmotors.com', 'Mohammed@123', 'staff', 'Head Office', 'JED-01', 'Parts Advisor'),
('Ali Mohammed Maki', 'ali.maki@jiadmotors.com', 'Ali@123', 'advisor', 'Alsafa', NULL, 'Service Advisor'),
('Hafiz Mohammed Sharif', 'hafiz.sharif@jiadmotors.com', 'Hafiz@123', 'advisor', 'Alsafa', NULL, 'Service Advisor'),
('Ahmed Elsayed Kamel Elsherif', 'Ahmed.Elsherif@jiadmotors.com', 'Ahmed@123', 'advisor', 'Khaldiah', 'DMM-01', 'Service advisor'),
('Abdellatif Ibrahim Abdellatif Ibrahim', 'Abdellatif.Ibrahim@jiadmotors.com', 'Abdellatif@123', 'staff', 'North', 'RUH-01', 'Quality Controller'),
('Fahad Mohammed Almari', 'fahad.almari@jiadmotors.com', 'Fahad@123', 'staff', 'North', 'RUH-01', 'Parts Advisor'),
('Musa Abdelrahman Mahgoub Mohamed Ahmed', 'Musa.Ahmed@jiadmotors.com​', 'Musa@123', 'staff', 'Alsafa', NULL, 'Workshop Team Leader'),
('Mohammed Ridha Ibrahim Shuayrah', 'Mohammed.Shuayrah@jiadmotors.com', 'Mohammed@123', 'advisor', 'Nakheel', 'JED-01', 'Service Advisor'),
('Mostafa Mahmoud Kamel Ali', 'mostafa.ali@jiadmotors.com', 'Mostafa@123', 'advisor', 'North', 'RUH-01', 'Service Advisor'),
('MOSTAFA IBRAHIM REDA ABOELNASR', 'Mostafa.Aboelnasr@jiadmotors.com', 'Mostafa@123', 'advisor', 'Alsalih', 'RUH-01', 'Service Advisor'),
('Abdalla Hassan Hallousa', 'Abdalla.Hallousa@jiadmotors.com', 'Abdalla@123', 'advisor', 'Airport Road', NULL, 'Service Advisor'),
('MOSTAFA MAGDY MOHAMED MAHMOUD', 'Mostafa.Mahmoud@jiadmotors.com', 'Mostafa@123', 'advisor', 'Hiraa', 'JED-01', 'Service Advisor'),
('YOUSSEF AHMED ALY HAMED', 'Youssef.Hamed@jiadmotors.com', 'Youssef@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Team Leader'),
('HESHAM MOHAMED TAHA ALI', 'Hesham.Ali@jiadmotors.com', 'Hesham@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Team Leader'),
('HAMED TAREK HAMED ELHITAMY', 'Hamed.Elhitamy@jiadmotors.com', 'Hamed@123', 'advisor', 'King Fahad', NULL, 'Service Advisor'),
('AMMAR MOHAMED NASEF TAWFIK', 'Ammar.Tawfik@jiadmotors.com', 'Ammar@123', 'advisor', 'North', 'RUH-01', 'Service Advisor'),
('MOSTAFA HAITHAM MOSTAFA ELDEEB', 'Mostafa.Eldeeb@jiadmotors.com', 'Mostafa@123', 'admin', 'Nakheel', 'JED-01', 'Workshop Contoller'),
('MOHAMMED IRFAN', 'mohammed.irfan@jiadmotors.com', 'Mohammed@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Team Leader'),
('AHMAD NASEER MUHAMMAD AJLAN', 'Ahmed.Ajlan@jiadmotors.com​', 'Ahmad@123', 'staff', 'Nakheel', 'JED-01', 'Quality Controller'),
('AHMAD ABDULLAH ATTIA', 'Ahmad.Attia@jiadmotors.com', 'Ahmad@123', 'staff', 'Alsalih', 'RUH-01', 'Workshop Team Leader'),
('AHMED HUSSEIN MOHAMED ALY', 'Ahmed.Aly@jiadmotors.com', 'Ahmed@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Team Leader'),
('KARIM MOHAMED OSAMA AMIN', 'Karim.Amin@jiadmotors.com', 'Karim@123', 'staff', 'North', 'RUH-01', 'Warranty Officer'),
('AMR ADEL MOSTAFA ABDELHAFEZ', 'Amr.Abdelhafez@jiadmotors.com', 'Amr@123', 'staff', 'North', 'RUH-01', 'Workshop Team Leader'),
('Mohammed Ahmed Gallab', 'mohammed.gallab@jiadmotors.com', 'Mohammed@123', 'staff', 'Alsafa', NULL, 'Workshop Contoller'),
('Saad Sarmini', 'saad.sarmini@jiadmotors.com', 'Saad@123', 'staff', 'Head Office', 'JED-01', 'Wholesale Parts Executive'),
('Saeed Rashed Alahmari', 'saeed.alahmari@jiadmotors.com', 'Saeed@123', 'advisor', 'King Fahad', NULL, 'Service Advisor'),
('Yousef Mohammed Alqhtani', 'yousef.alqhtani@jiadmotors.com', 'Yousef@123', 'staff', 'King Fahad', NULL, 'Receptionist'),
('Ahmed Naef Alharbi', 'Ahmed.Naef@jiadmotors.com', 'Ahmed@123', 'advisor', 'Buraidah', NULL, 'Service Advisor'),
('Mohammed Abdulaziz Albadia', 'mohammed.albadia@jiadmotors.com', 'Mohammed@123', 'advisor', 'Khurais', 'RUH-01', 'Service Advisor'),
('Abdulrahman Mohammed Haqawi', 'abdulrahman.haqawi@jiadmotors.com', 'Abdulrahman@123', 'staff', 'King Fahad', NULL, 'Parts Advisor'),
('Ahmed Mohammed Bahifth Allah', 'ahmed.bahifth@jiadmotors.com', 'Ahmed@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Advisor'),
('Ahmed Mohammed Alamoodi', 'ahmed.alamoodi@jiadmotors.com', 'Ahmed@123', 'staff', 'Nakheel', 'JED-01', 'Quality Controller'),
('Mohamed Atef Ahmed', 'mohamed.atef.ahmed@jiadmotors.com', 'Mohamed@123', 'staff', 'North', 'RUH-01', 'Diagnostics Technician'),
('Ahmed Ashraf Khalil', 'ahmed.khalil@jiadmotors.com', 'Ahmed@123', 'staff', 'Hiraa', 'JED-01', 'Workshop Team Leader'),
('Mostafa Magdy Aboshahba', 'mostafa.aboshahba@jiadmotors.com', 'Mostafa@123', 'staff', 'North', 'RUH-01', 'Workshop Team Leader'),
('Amirah Abdulaziz Saleh Alghamdi', 'Ameera.Alghamdi@jiadmotors.com', 'Amirah@123', 'staff', 'Hiraa', 'JED-01', 'Receptionist'),
('Ali Mohammed Ali Alahmri', 'Ali.Alahmri@jiadmotors.com', 'Ali@123', 'staff', 'Hiraa', 'JED-01', 'Parts Advisor'),
('Muhannad Faisal Mohamed Almadani', 'Muhannad.Almadani@jiadmotors.com', 'Muhannad@123', 'staff', 'Khurais', 'RUH-01', 'Parts Advisor'),
('Salem Ali Hasan Alfahimi', 'Salem.Alfahimi@jiadmotors.com', 'Salem@123', 'staff', 'Hiraa', 'JED-01', 'Parts Advisor'),
('Mohammed Saeed Abdullah Alabd', 'mohammed.alabed@jiadmotors.com', 'Mohammed@123', 'staff', 'King Fahad', NULL, 'Parts Advisor'),
('Yousef Alhazmi', 'yousef.alhazmi@jiadmotors.com', 'Yousef@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Javed Alam MD Moosa', 'javed.alam.md.moosa@jiadmotors.com', 'Javed@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Abdulbari Abbas', 'abdulbari.abbas@jiadmotors.com', 'Abdulbari@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Sonny Zabala', 'sonny.zabala@jiadmotors.com', 'Sonny@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Abdullah Abdelsalam', 'abdullah.abdelsalam@jiadmotors.com', 'Abdullah@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Mohammed Mutlak', 'mohammed.mutlak@jiadmotors.com', 'Mohammed@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('MUDASSAR CONTRACTOR', 'mudassar.contractor@jiadmotors.com', 'Mudassar@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('PRASANTH JAGADEESWARAN', 'prasanth.jagadeeswaran@jiadmotors.com', 'Prasanth@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('SAMEEL NANGALATH PUTHIYAPURAYIL', 'sameel.nangalath.puthiyapurayil@jiadmotors.com', 'Sameel@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('MIDHUN PLAVUMKAL CHACKO', 'midhun.plavumkal.chacko@jiadmotors.com', 'Midhun@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('SANDESH SHETTY', 'sandesh.shetty@jiadmotors.com', 'Sandesh@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('SAYANTH UCHUMMAL', 'sayanth.uchummal@jiadmotors.com', 'Sayanth@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('AKHIL ANTONY VARGHESE', 'akhil.antony.varghese@jiadmotors.com', 'Akhil@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('ARUN PANDARIKKAL', 'arun.pandarikkal@jiadmotors.com', 'Arun@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('JISHNU PAYAROLITHAZHA KUNIYIL', 'jishnu.payarolithazha.kuniyil@jiadmotors.com', 'Jishnu@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('JITHIN THOOMBAYIL RAJ', 'jithin.thoombayil.raj@jiadmotors.com', 'Jithin@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('MUHAMMED HASEEN V MUHAMMED ALI', 'muhammed.haseen.v.muhammed.ali@jiadmotors.com', 'Muhammed@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('YOGESH PATIL', 'yogesh.patil@jiadmotors.com', 'Yogesh@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('RAKSHITH BEEDU', 'rakshith.beedu@jiadmotors.com', 'Rakshith@123', 'staff', 'Madinah Road', 'JED-01', 'Repair Technician'),
('Julito Competente', 'julito.competente@jiadmotors.com', 'Julito@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('Muhammed Shereef Ambukkadan', 'muhammed.shereef.ambukkadan@jiadmotors.com', 'Muhammed@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('Shamjith Valakkada', 'shamjith.valakkada@jiadmotors.com', 'Shamjith@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Anoop Cheenikottil', 'anoop.cheenikottil@jiadmotors.com', 'Anoop@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Shailesh Sathisha Poojary', 'shailesh.sathisha.poojary@jiadmotors.com', 'Shailesh@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Tamer Moustafa Elnady', 'tamer.elnady@jiadmotors.com', 'Tamer@123', 'manager', 'Head Office', 'JED-01', 'Aftersales Director'),
('Sujesh Koriyattil', 'sujesh.koriyattil@jiadmotors.com', 'Sujesh@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Jose Rison', 'jose.rison@jiadmotors.com', 'Jose@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Vivek Muraleedharan', 'vivek.muraleedharan@jiadmotors.com', 'Vivek@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('Vasantha Chavadi', 'vasantha.chavadi@jiadmotors.com', 'Vasantha@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Shuaib Bdrudeen Bdrudeen A', 'Shuaib.Badarudeen@jiadmotors.com​', 'Shuaib@123', 'staff', 'Head Office', 'JED-01', 'Warranty Officer'),
('MOHAMED SHEMEEM THOTTIYIL', 'mohamed.shemeem.thottiyil@jiadmotors.com', 'Mohamed@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('ATHUL KATTERI', 'athul.katteri@jiadmotors.com', 'Athul@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('PAVAN NAGABHU SHAN SHIVAMOGGA', 'pavan.nagabhu.shan.shivamogga@jiadmotors.com', 'Pavan@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('AJEESH CHUKKAMKONAM ARUMUGHAN', 'ajeesh.chukkamkonam.arumughan@jiadmotors.com', 'Ajeesh@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('MUHAMMED ALTHAF KAKKATTUCHALI', 'muhammed.althaf.kakkattuchali@jiadmotors.com', 'Muhammed@123', 'staff', 'Madinah Road', 'JED-01', 'Repair Technician'),
('Waleed Aboubakr Ibrahim', 'waleed.aboubakr.ibrahim@jiadmotors.com', 'Waleed@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Yaser Abdulrahman Damen', 'yaser.abdulrahman.damen@jiadmotors.com', 'Yaser@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('Fahad Khan Afsar', 'fahad.khan.afsar@jiadmotors.com', 'Fahad@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('MUSAMMIL MULLANTAKATH', 'musammil.mullantakath@jiadmotors.com', 'Musammil@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('VIGNESHA VASUDEVA', 'vignesha.vasudeva@jiadmotors.com', 'Vignesha@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('Turki Sunari', 'turki.sunari@jiadmotors.com', 'Turki@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('MUHAMMED AFTHAB PAIKKATTU CHALI', 'muhammed.afthab.paikkattu.chali@jiadmotors.com', 'Muhammed@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('MUHAMMED NASEEF MELEDATH', 'muhammed.naseef.meledath@jiadmotors.com', 'Muhammed@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('ANTONY JOY', 'antony.joy@jiadmotors.com', 'Antony@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('BINU VARAPPURATHU BABUKUTTAN', 'binu.varappurathu.babukuttan@jiadmotors.com', 'Binu@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('BIBIN PRASAD', 'bibin.prasad@jiadmotors.com', 'Bibin@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('DHEERAJ KALATHUPURATH RAJAN', 'dheeraj.kalathupurath.rajan@jiadmotors.com', 'Dheeraj@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('NIKHILRAJ PERUMTHODI', 'nikhilraj.perumthodi@jiadmotors.com', 'Nikhilraj@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('SHIJIN PLAKANDIYIL', 'shijin.plakandiyil@jiadmotors.com', 'Shijin@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('ELDHOSE PULICHOTTIL PAULOSE', 'eldhose.pulichottil.paulose@jiadmotors.com', 'Eldhose@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('SMIJITH KAPLINGATTU SUBRAMANIAN', 'smijith.kaplingattu.subramanian@jiadmotors.com', 'Smijith@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('HARIKRISHNAN MAPPILAKUNNEL SAJI', 'harikrishnan.mappilakunnel.saji@jiadmotors.com', 'Harikrishnan@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('DHILIBAN DEENADAYALAN', 'dhiliban.deenadayalan@jiadmotors.com', 'Dhiliban@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('BIPIN CHERUPARAMBIL SEBASTIAN', 'bipin.cheruparambil.sebastian@jiadmotors.com', 'Bipin@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('AJO SHAIJAN', 'ajo.shaijan@jiadmotors.com', 'Ajo@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('SHAJEER ABDUL SALEEM', 'shajeer.abdul.saleem@jiadmotors.com', 'Shajeer@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('SEMEER NELLIKKAL', 'semeer.nellikkal@jiadmotors.com', 'Semeer@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('Wilbert Combo Margallo', 'wilbert.combo.margallo@jiadmotors.com', 'Wilbert@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('Rakan Saad Almalki', 'rakan.saad.almalki@jiadmotors.com', 'Rakan@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Mohammed Ethasham Mohammed Irfan', 'mohammed.ethasham.mohammed.irfan@jiadmotors.com', 'Mohammed@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('Mahamat Abdallah Dogo Ali', 'mahamat.abdallah.dogo.ali@jiadmotors.com', 'Mahamat@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Rochdi Mohamed Ben Romdhane', 'rochdi.mohamed.ben.romdhane@jiadmotors.com', 'Rochdi@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('Arnold Asuncion Adiaz', 'arnold.asuncion.adiaz@jiadmotors.com', 'Arnold@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('BILAL AHMED KHALID AMIN', 'bilal.ahmed.khalid.amin@jiadmotors.com', 'Bilal@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('BELAL MAHMOUD IBRAHIM KHALIL', 'belal.mahmoud.ibrahim.khalil@jiadmotors.com', 'Belal@123', 'staff', 'Alsafa', NULL, 'Repair Technician'),
('MAHMOUD FAWZY ABDELMOTELEB ELSAYED', 'mahmoud.fawzy.abdelmoteleb.elsayed@jiadmotors.com', 'Mahmoud@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('ANSAR BABU', 'ansar.babu@jiadmotors.com', 'Ansar@123', 'staff', 'Airport Road', NULL, 'Repair Technician'),
('NAGARAJ PRAKASH JADHAV', 'nagaraj.prakash.jadhav@jiadmotors.com', 'Nagaraj@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('PRAMOD MOORKATHODI', 'pramod.moorkathodi@jiadmotors.com', 'Pramod@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('SANOOP POOKKULAYAN', 'sanoop.pookkulayan@jiadmotors.com', 'Sanoop@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('UZER PASHA', 'uzer.pasha@jiadmotors.com', 'Uzer@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('KRISHNADAS THALAKKATTE', 'krishnadas.thalakkatte@jiadmotors.com', 'Krishnadas@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('JAMSHAD ANKALAM', 'jamshad.ankalam@jiadmotors.com', 'Jamshad@123', 'staff', 'Buraidah', NULL, 'Repair Technician'),
('LIJIN MANNOORKKARA', 'lijin.mannoorkkara@jiadmotors.com', 'Lijin@123', 'staff', 'Buraidah', NULL, 'Repair Technician'),
('RANJITH KUNNATHAM PARAMBIL CHAMI', 'ranjith.kunnatham.parambil.chami@jiadmotors.com', 'Ranjith@123', 'staff', 'Buraidah', NULL, 'Repair Technician'),
('AMEY RAMAKANT DESSAI', 'amey.ramakant.dessai@jiadmotors.com', 'Amey@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('KAILAS CHEMBRA VELAYUDHAN', 'kailas.chembra.velayudhan@jiadmotors.com', 'Kailas@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('MANISH MANOHAR GURAV', 'manish.manohar.gurav@jiadmotors.com', 'Manish@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('MURUGESAN KUMARASAMY', 'murugesan.kumarasamy@jiadmotors.com', 'Murugesan@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician'),
('AMAL CHALIL POTTAMMAL', 'amal.chalil.pottammal@jiadmotors.com', 'Amal@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('NIKHIL THESSERY RAJAN', 'nikhil.thessery.rajan@jiadmotors.com', 'Nikhil@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('SUBRAHMANYA KOTI NAIK', 'subrahmanya.koti.naik@jiadmotors.com', 'Subrahmanya@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('THILAK SUNDARA POOJARY', 'thilak.sundara.poojary@jiadmotors.com', 'Thilak@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('MANICKAM MUTHIYA', 'manickam.muthiya@jiadmotors.com', 'Manickam@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('SATHISHA GOWDA', 'sathisha.gowda@jiadmotors.com', 'Sathisha@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('RAMITH BILLAVA SHESHAPPA', 'ramith.billava.sheshappa@jiadmotors.com', 'Ramith@123', 'staff', 'Khaldiah', 'DMM-01', 'Repair Technician'),
('ELDHOSE JOLLY', 'eldhose.jolly@jiadmotors.com', 'Eldhose@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('AKASH SANTHOSH', 'akash.santhosh@jiadmotors.com', 'Akash@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('JOYAL VARGHESE', 'joyal.varghese@jiadmotors.com', 'Joyal@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('AKSHAY SOMAN VALLIKKOL', 'akshay.soman.vallikkol@jiadmotors.com', 'Akshay@123', 'staff', 'Khurais', 'RUH-01', 'Repair Technician'),
('Abdullah Bazyad', 'abdullah.bazyad@jiadmotors.com', 'Abdullah@123', 'staff', 'Madinah Road', 'JED-01', 'Repair Technician'),
('NIZAMUDDIN ISMAIL KHOPATKAR', 'nizamuddin.ismail.khopatkar@jiadmotors.com', 'Nizamuddin@123', 'staff', 'Madinah Road', 'JED-01', 'Repair Technician'),
('AKHIL VAKAYIL MURALI', 'akhil.vakayil.murali@jiadmotors.com', 'Akhil@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('DON KOZHIKKADAN LONAPPAN', 'don.kozhikkadan.lonappan@jiadmotors.com', 'Don@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('DEEPAK MANUKKADAN SURENDRAN', 'deepak.manukkadan.surendran@jiadmotors.com', 'Deepak@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('SAJEESH KALARI PARAMBATH', 'sajeesh.kalari.parambath@jiadmotors.com', 'Sajeesh@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('ABHINAV KOOLI', 'abhinav.kooli@jiadmotors.com', 'Abhinav@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('NIKHIL PETER', 'nikhil.peter@jiadmotors.com', 'Nikhil@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('MAHBOOB MIYAN', 'mahboob.miyan@jiadmotors.com', 'Mahboob@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('Adnan Bin Mahfooz', 'adnan.bin.mahfooz@jiadmotors.com', 'Adnan@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('JOJO PORATHUR JOHNSON', 'jojo.porathur.johnson@jiadmotors.com', 'Jojo@123', 'staff', 'Alsalih', 'RUH-01', 'Repair Technician'),
('MANIKANDAN MOHANAN', 'manikandan.mohanan@jiadmotors.com', 'Manikandan@123', 'staff', 'King Fahad', NULL, 'Repair Technician'),
('ANSHAD MATTUVAYAL', 'anshad.mattuvayal@jiadmotors.com', 'Anshad@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('AHAMED SAJID ARANGATHIL', 'ahamed.sajid.arangathil@jiadmotors.com', 'Ahamed@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('VISHNU SOMAN', 'vishnu.soman@jiadmotors.com', 'Vishnu@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Ghayoor Akhtar Baluchi', 'ghayoor.akhtar.baluchi@jiadmotors.com', 'Ghayoor@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Mohammed Ahmed Ghassan Alothman', 'mohammed.ahmed.ghassan.alothman@jiadmotors.com', 'Mohammed@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Hassan Yasir Abdullah Alsinan', 'hassan.yasir.abdullah.alsinan@jiadmotors.com', 'Hassan@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Fahad Waheed Mohammed Rasheed Saad', 'fahad.waheed.mohammed.rasheed.saad@jiadmotors.com', 'Fahad@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Abdulaziz Abdullah Dhaifullah Alqurashi', 'abdulaziz.abdullah.dhaifullah.alqurashi@jiadmotors.com', 'Abdulaziz@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Hamzah Emad Mohammed Kashmiri', 'hamzah.emad.mohammed.kashmiri@jiadmotors.com', 'Hamzah@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Ibrahim Ahmed Abdullah Jaafari', 'ibrahim.ahmed.abdullah.jaafari@jiadmotors.com', 'Ibrahim@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Mohammed Ahmed Ali Athlawi', 'mohammed.ahmed.ali.athlawi@jiadmotors.com', 'Mohammed@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Rayan Mohammed Ahmed Mohammed', 'rayan.mohammed.ahmed.mohammed@jiadmotors.com', 'Rayan@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Abdullah Sami Abdullah Albahrani', 'abdullah.sami.abdullah.albahrani@jiadmotors.com', 'Abdullah@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Abbas Helal Hasan Alnazgah', 'abbas.helal.hasan.alnazgah@jiadmotors.com', 'Abbas@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Abdulhadi Shaker Mohamed Alshehri', 'abdulhadi.shaker.mohamed.alshehri@jiadmotors.com', 'Abdulhadi@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Marwan Mohammed Jaafr Alrashdi', 'marwan.mohammed.jaafr.alrashdi@jiadmotors.com', 'Marwan@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Saleh Khalid Saleh Alfalaj', 'saleh.khalid.saleh.alfalaj@jiadmotors.com', 'Saleh@123', 'staff', 'Hiraa', 'JED-01', 'Mechanic Trainee'),
('Junaid Ahmed Khan', 'junaid.ahmed.khan@jiadmotors.com', 'Junaid@123', 'staff', 'North', 'RUH-01', 'Repair Technician'),
('ABDULLAH ARSHAD  MUHAMMAD  QURESHI', 'abdullah.arshad.muhammad.qureshi@jiadmotors.com', 'Abdullah@123', 'staff', 'Madinah Road', 'JED-01', 'Repair Technician'),
('Fayaz Sayed', 'fayaz.sayed@jiadmotors.com', 'Fayaz@123', 'staff', 'Hiraa', 'JED-01', 'Parts Picker'),
('Khalid Salih Osman', 'khalid.salih.osman@jiadmotors.com', 'Khalid@123', 'staff', 'Buraidah', NULL, 'Parts Picker'),
('Afsar Shah', 'afsar.shah@jiadmotors.com', 'Afsar@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Picker'),
('Zakir Bukhsh', 'zakir.bukhsh@jiadmotors.com', 'Zakir@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Picker'),
('Shoaib khan', 'shoaib.khan@jiadmotors.com', 'Shoaib@123', 'staff', 'Khaldiah', 'DMM-01', 'Parts Picker'),
('ABDULLAH ISMAIL SHAHNUR', 'abdullah.ismail.shahnur@jiadmotors.com', 'Abdullah@123', 'staff', 'Hiraa', 'JED-01', 'Parts Picker'),
('Adel Adres', 'adel.adres@jiadmotors.com', 'Adel@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Picker'),
('AhmadMahboob Mahboobulhaq', 'ahmadmahboob.mahboobulhaq@jiadmotors.com', 'Ahmadmahboob@123', 'staff', 'Airport Road', NULL, 'Parts Picker'),
('Ali Masoud Aldahbali', 'ali.masoud.aldahbali@jiadmotors.com', 'Ali@123', 'staff', 'King Fahad', NULL, 'Parts Picker'),
('Ibrahim Tahir Adbraman', 'ibrahim.tahir.adbraman@jiadmotors.com', 'Ibrahim@123', 'staff', 'Nakheel', 'JED-01', 'Parts Picker'),
('Rubel Miah Hanif Miah', 'rubel.miah.hanif.miah@jiadmotors.com', 'Rubel@123', 'staff', 'North', 'RUH-01', 'Parts Picker'),
('Hozaifa Mohammed Ali Idris', 'hozaifa.mohammed.ali.idris@jiadmotors.com', 'Hozaifa@123', 'staff', 'North', 'RUH-01', 'Parts Picker'),
('Al-Amin Abdul Gani - Huwlader', 'alamin.abdul.gani.huwlader@jiadmotors.com', 'Alamin@123', 'staff', 'Nakheel', 'JED-01', 'Parts Picker'),
('Yahya Mohammed Bakheet', 'yahya.mohammed.bakheet@jiadmotors.com', 'Yahya@123', 'staff', 'Alsafa', NULL, 'Parts Picker'),
('Hasem Md Abulkalam', 'hasem.md.abulkalam@jiadmotors.com', 'Hasem@123', 'staff', 'Airport Road', NULL, 'Parts Picker'),
('Alhussien Sireur Ahmedden', 'alhussien.sireur.ahmedden@jiadmotors.com', 'Alhussien@123', 'staff', 'Khurais', 'RUH-01', 'Parts Picker'),
('Muhammad Bilalamjad', 'muhammad.bilalamjad@jiadmotors.com', 'Muhammad@123', 'staff', 'King Fahad', NULL, 'Parts Picker'),
('Omor Faruk', 'omor.faruk@jiadmotors.com', 'Omor@123', 'staff', 'Hiraa', 'JED-01', 'Parts Picker'),
('Muhammad Muzammal Muhammad Saqib', 'muhammad.muzammal.muhammad.saqib@jiadmotors.com', 'Muhammad@123', 'staff', 'Alsalih', 'RUH-01', 'Parts Picker'),
('Turki Khinab', 'turki.khinab@jiadmotors.com', 'Turki@123', 'staff', 'Hiraa', 'JED-01', 'Driver'),
('Mahmoud Hamid', 'mahmoud.hamid@jiadmotors.com', 'Mahmoud@123', 'staff', 'Alsalih', 'RUH-01', 'Driver'),
('Mohamednoor ALi', 'mohamednoor.ali@jiadmotors.com', 'Mohamednoor@123', 'staff', 'Alsalih', 'RUH-01', 'Driver'),
('Haitham Ali', 'haitham.ali@jiadmotors.com', 'Haitham@123', 'staff', 'Khaldiah', 'DMM-01', 'Driver'),
('Bakri Dirar', 'bakri.dirar@jiadmotors.com', 'Bakri@123', 'staff', 'Nakheel', 'JED-01', 'Driver'),
('Ali Salih Diwaed', 'ali.salih.diwaed@jiadmotors.com', 'Ali@123', 'staff', 'Airport Road', NULL, 'Driver'),
('Hashim Osman Hamid Ali', 'hashim.osman.hamid.ali@jiadmotors.com', 'Hashim@123', 'staff', 'Alsafa', NULL, 'Driver'),
('Ahmed Osman Ahmed Ali', 'ahmed.osman.ahmed.ali@jiadmotors.com', 'Ahmed@123', 'staff', 'North', 'RUH-01', 'Driver'),
('Mosaab Mohamed Jemea Mahmoud', 'mosaab.mohamed.jemea.mahmoud@jiadmotors.com', 'Mosaab@123', 'staff', 'North', 'RUH-01', 'Driver'),
('Omer Derar Mohammed', 'omer.derar.mohammed@jiadmotors.com', 'Omer@123', 'staff', 'Alsalih', 'RUH-01', 'Driver'),
('Mohammed Shoei Helal', 'mohammed.shoei.helal@jiadmotors.com', 'Mohammed@123', 'staff', 'Hiraa', 'JED-01', 'Driver'),
('Mahammadazam Mahammadbuata', 'mahammadazam.mahammadbuata@jiadmotors.com', 'Mahammadazam@123', 'staff', 'Hiraa', 'JED-01', 'Driver'),
('Abdullah Abdulaziz Ahmed', 'abdullah.abdulaziz.ahmed@jiadmotors.com', 'Abdullah@123', 'staff', 'King Fahad', NULL, 'Driver'),
('Alamin Suleman Mhmoud', 'alamin.suleman.mhmoud@jiadmotors.com', 'Alamin@123', 'staff', 'Khaldiah', 'DMM-01', 'Driver'),
('Mouid Maziad Alosman', 'mouid.maziad.alosman@jiadmotors.com', 'Mouid@123', 'advisor', 'Hiraa', 'JED-01', 'Service Advisor'),
('Jamal Elsnari', 'jamal.elsnari@jiadmotors.com', 'Jamal@123', 'staff', 'Nakheel', 'JED-01', 'Repair Technician'),
('Ali Nasser Asiri', 'ali.nasser.asiri@jiadmotors.com', 'Ali@123', 'staff', 'Hiraa', 'JED-01', 'Repair Technician');
